### ISSUE TITLE
why can't get metrics 

### ISSUE THREAD

**Issue by tripitakav** [mumoshu/prometheus-process-exporter#17]
```yaml
---
# Source: prometheus-process-exporter/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: prometheus-process-exporter
  name: release-name-prometheus-process-exporter
spec:
  privileged: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
  hostNetwork: true
  hostIPC: false
  hostPID: true
  hostPorts:
    - min: 0
      max: 65535
  runAsUser:
    # Permits the container to run with root privileges as well.
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
  readOnlyRootFilesystem: false
---
# Source: prometheus-process-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-prometheus-process-exporter
  labels:
    app: prometheus-process-exporter
automountServiceAccountToken: true
---
# Source: prometheus-process-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: alert
  name: release-name-prometheus-process-exporter
  labels:
    app: prometheus-process-exporter
data:
  config.yml: |-
    process_names:
      - name: "{{.Comm}}"
        cmdline:
        - '.+'
---
# Source: prometheus-process-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: prometheus-process-exporter
  name: psp-release-name-prometheus-process-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - release-name-prometheus-process-exporter
---
# Source: prometheus-process-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-process-exporter
  name: psp-release-name-prometheus-process-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-release-name-prometheus-process-exporter
subjects:
  - kind: ServiceAccount
    name: release-name-prometheus-process-exporter
    namespace: alert
---
# Source: prometheus-process-exporter/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: alert
  name: prometheus-process-exporter
  labels:
    app: prometheus-process-exporter
spec:
  selector:
    matchLabels:
      app: prometheus-process-exporter
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-process-exporter
    spec:
      serviceAccountName: release-name-prometheus-process-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: prometheus-process-exporter
          image: xxx
          imagePullPolicy: IfNotPresent
          args:
            - --procfs=/host/proc
            - --config.path=/var/process-exporter/config.yml
            - --web.listen-address=0.0.0.0:9256
            - --debug=true
          ports:
            - containerPort: 9256
          resources:
            requests:
              cpu: 120m
              memory: 120Mi
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: config
              mountPath: /var/process-exporter
      hostPID: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: release-name-prometheus-process-exporter
```

![image](https://user-images.githubusercontent.com/73687556/202951546-c7e570d2-03e3-4047-974c-e747627254f5.png)

I think the pod is running normally. Why can't I get metrics through K8s node ip: 9256/metrics？

![image](https://user-images.githubusercontent.com/73687556/202951882-201d95d0-5534-48f0-8f74-558fb46657bf.png)
I want to enter the container to check the problem, but an error is reported！
