### ISSUE TITLE
securityContext value not implemented

### ISSUE THREAD

**Issue by lumi017** [mumoshu/prometheus-process-exporter#2]
You have the following values
```
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
```
However they are not used anywhere in the chart. In the PSP you have
```
runAsUser:
    # Permits the container to run with root privileges as well.
    rule: 'RunAsAny'`
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 0
        max: 65535
```
The logic wasn't implemented
